<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 2</b></center>    
<pre>



### Step 1. Import the necessary libraries

In [20]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [21]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. See the first 25 entries

In [26]:
df.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [27]:
df.tail(10)

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [28]:

df.shape

(943, 5)

### Step 7. What is the number of columns in the dataset?

In [29]:
df.shape[1]

5

### Step 8. Print the name of all the columns.

In [30]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='str')

### Step 9. How is the dataset indexed?

In [31]:
df.index

RangeIndex(start=0, stop=943, step=1)

### Step 10. What is the data type of each column?

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

### Step 11. Print only the occupation column

In [33]:
df['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

### Step 12. How many different occupations are in this dataset?

In [36]:
df["occupation"].unique()

<StringArray>
[   'technician',         'other',        'writer',     'executive',
 'administrator',       'student',        'lawyer',      'educator',
     'scientist', 'entertainment',    'programmer',     'librarian',
     'homemaker',        'artist',      'engineer',     'marketing',
          'none',    'healthcare',       'retired',      'salesman',
        'doctor']
Length: 21, dtype: str

### Step 13. What is the most frequent occupation?

In [39]:
df["occupation"].value_counts().head(5)

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [40]:
df.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### Step 15. Summarize all the columns

In [41]:
df.describe(include="all")

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [42]:
df["occupation"].describe(include = "object")

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [43]:
df['age'].mean()

np.float64(34.05196182396607)

### Step 18. What is the age with least occurrence?

In [44]:
df['age'].min()

np.int64(7)

## Part -2

- **All tasks** are based on the **single dataset** loaded in the Setup cell below.

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 200

cities    = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
             'Philadelphia', 'San Antonio', 'Dallas', 'Austin', 'Seattle']
regions   = {'New York': 'East', 'Los Angeles': 'West', 'Chicago': 'North',
             'Houston': 'South', 'Phoenix': 'West', 'Philadelphia': 'East',
             'San Antonio': 'South', 'Dallas': 'South', 'Austin': 'South', 'Seattle': 'West'}
categories = ['Electronics', 'Clothing', 'Food', 'Furniture']
products   = {
    'Electronics': ['Laptop', 'Smartphone', 'Headphones', 'Tablet', 'Camera'],
    'Clothing':    ['T-Shirt', 'Jeans', 'Jacket', 'Sneakers', 'Dress'],
    'Food':        ['Coffee Beans', 'Olive Oil', 'Pasta', 'Chocolate', 'Tea'],
    'Furniture':   ['Office Chair', 'Desk', 'Bookshelf', 'Sofa', 'Lamp']
}
prices     = {
    'Laptop': 999.99, 'Smartphone': 799.99, 'Headphones': 199.99,
    'Tablet': 499.99, 'Camera': 649.99, 'T-Shirt': 29.99,
    'Jeans': 59.99, 'Jacket': 89.99, 'Sneakers': 79.99, 'Dress': 69.99,
    'Coffee Beans': 14.99, 'Olive Oil': 12.99, 'Pasta': 5.99,
    'Chocolate': 8.99, 'Tea': 9.99, 'Office Chair': 249.99,
    'Desk': 349.99, 'Bookshelf': 149.99, 'Sofa': 799.99, 'Lamp': 49.99
}
salespersons = ['Alice Johnson', 'Bob Martinez', 'Carol White',
                'David Lee', 'Emma Davis']
first_names  = ['James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer',
                'Michael', 'Linda', 'William', 'Barbara', 'David', 'Susan',
                'Richard', 'Jessica', 'Thomas', 'Sarah', 'Charles', 'Karen',
                'Daniel', 'Lisa']
last_names   = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia',
                'Miller', 'Davis', 'Wilson', 'Moore', 'Taylor', 'Anderson',
                'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson',
                'Young', 'Robinson']

city_list    = np.random.choice(cities, n)
cat_list     = np.random.choice(categories, n)
prod_list    = [np.random.choice(products[c]) for c in cat_list]
price_list   = np.array([prices[p] for p in prod_list])
disc_list    = np.random.choice([0, 5, 10, 15, 20, 25, 30], n)
qty_list     = np.random.randint(1, 11, n)
rating_list  = np.random.choice([1, 2, 3, 4, 5], n, p=[0.05, 0.10, 0.20, 0.40, 0.25])
dates        = pd.date_range(start='2023-01-01', end='2023-12-31', periods=n)
dates        = pd.to_datetime(np.sort(np.random.choice(dates, n, replace=False)))
cust_names   = [f"{np.random.choice(first_names)} {np.random.choice(last_names)}" for _ in range(n)]

# Introduce some missing values
rating_arr = rating_list.astype(float)
rating_arr[np.random.choice(n, 12, replace=False)] = np.nan
disc_arr = disc_list.astype(float)
disc_arr[np.random.choice(n, 8, replace=False)] = np.nan

df = pd.DataFrame({
    'order_id':      [f'ORD-{1000+i}' for i in range(n)],
    'order_date':    dates,
    'customer_name': cust_names,
    'city':          city_list,
    'region':        [regions[c] for c in city_list],
    'category':      cat_list,
    'product':       prod_list,
    'quantity':      qty_list,
    'unit_price':    price_list,
    'discount':      disc_arr,
    'salesperson':   np.random.choice(salespersons, n),
    'rating':        rating_arr
})

# Add duplicate rows intentionally
df = pd.concat([df, df.iloc[[5, 23, 77]]], ignore_index=True)


df.head()

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0

### ✅ Task 1 — First Inspection
Perform a basic inspection of the DataFrame `df`:
1. Display the **first 8 rows**.
2. Display the **last 5 rows**.
3. Print the **shape** (rows, columns).
4. Print all **column names**.

In [ ]:
df.head(8)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0
5,ORD-1005,2023-01-10 03:29:50.954773,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
6,ORD-1006,2023-01-11 23:23:49.145728,Mary Williams,Chicago,North,Electronics,Laptop,5,999.99,15.0,Emma Davis,NaN
7,ORD-1007,2023-01-13 19:17:47.336683,Robert Taylor,San Antonio,South,Furniture,Bookshelf,6,149.99,20.0,Alice Johnson,5.0

In [9]:
df.tail(5)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
198,ORD-1198,2023-12-29 04:06:01.809045,Robert Brown,Los Angeles,West,Food,Tea,4,9.99,0.0,Alice Johnson,4.0
199,ORD-1199,2023-12-31 00:00:00.000000,Susan Robinson,Philadelphia,East,Clothing,Dress,6,69.99,10.0,Bob Martinez,NaN
200,ORD-1005,2023-01-10 03:29:50.954773,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
201,ORD-1023,2023-02-12 01:41:18.391959,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,NaN
202,ORD-1077,2023-05-21 20:15:40.703517,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0

In [10]:
df.shape

(203, 12)

In [11]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'city', 'region', 'category',
       'product', 'quantity', 'unit_price', 'discount', 'salesperson',
       'rating'],
      dtype='str')

### ✅ Task 2 — Data Types & Info
1. Display the **data type** of each column using `.dtypes`.
2. Use `.info()` to get a full summary.
3. Identify which columns have **missing values** and how many.

In [46]:

df.dtypes

order_id                    str
order_date       datetime64[us]
customer_name               str
city                        str
region                      str
category                    str
product                     str
quantity                  int64
unit_price              float64
discount                float64
salesperson                 str
rating                  float64
dtype: object

In [47]:
df.info

<bound method DataFrame.info of      order_id                 order_date     customer_name          city  \
0    ORD-1000 2023-01-01 00:00:00.000000    Karen Robinson   San Antonio
1    ORD-1001 2023-01-02 19:53:58.190954  Michael Williams       Houston
2    ORD-1002 2023-01-04 15:47:56.381909       Karen Moore        Dallas
3    ORD-1003 2023-01-06 11:41:54.572864    Michael Martin       Phoenix
4    ORD-1004 2023-01-08 07:35:52.763819  Jessica Williams   San Antonio
..        ...                        ...               ...           ...
198  ORD-1198 2023-12-29 04:06:01.809045      Robert Brown   Los Angeles
199  ORD-1199 2023-12-31 00:00:00.000000    Susan Robinson  Philadelphia
200  ORD-1005 2023-01-10 03:29:50.954773      Susan Thomas       Seattle
201  ORD-1023 2023-02-12 01:41:18.391959  Michael Robinson  Philadelphia
202  ORD-1077 2023-05-21 20:15:40.703517       Sarah Davis        Austin

    region     category       product  quantity  unit_price  discount  \
0    South     Clothing        Jacket         1       89.99      10.0
1    South         Food     Olive Oil         5       12.99      15.0
2    South         Food     Olive Oil         7       12.99       0.0
3     West    Furniture          Desk         6      349.99      15.0
4    South    Furniture  Office Chair         1      249.99      10.0
..     ...          ...           ...       ...         ...       ...
198   West         Food           Tea         4        9.99       0.0
199   East     Clothing         Dress         6       69.99      10.0
200   West  Electronics        Laptop         5      999.99      20.0
201   East    Furniture     Bookshelf         1      149.99      10.0
202  South         Food           Tea         2        9.99       5.0

       salesperson  rating
0        David Lee     5.0
1        David Lee     4.0
2     Bob Martinez     NaN
3        David Lee     5.0
4       Emma Davis     4.0
..             ...     ...
198  Alice Johnson     4.0
199   Bob Martinez     NaN
200     Emma Davis     4.0
201     Emma Davis     NaN
202   Bob Martinez     4.0

[203 rows x 12 columns]>

In [48]:
df.isnull().sum()

order_id          0
order_date        0
customer_name     0
city              0
region            0
category          0
product           0
quantity          0
unit_price        0
discount          8
salesperson       0
rating           13
dtype: int64

### ✅ Task 3 — Descriptive Statistics
1. Use `.describe()` to get summary statistics for **all numeric columns**.
2. Use `.describe(include='object')` to get statistics for **text columns**.
3. Print the **mean**, **min**, and **max** of `unit_price` separately.

In [49]:
df.describe()

,order_date,quantity,unit_price,discount,rating
count,203,203.000000,203.0000,195.000000,190.000000
mean,2023-06-30 06:09:17.684976,5.389163,274.1033,14.692308,3.810526
min,2023-01-01 00:00:00,1.000000,5.9900,0.000000,1.000000
25%,2023-03-30 17:07:32.261306,3.000000,29.9900,5.000000,3.000000
50%,2023-06-29 06:09:02.713567,5.000000,89.9900,15.000000,4.000000
75%,2023-09-29 15:04:31.356783,8.000000,424.9900,20.000000,5.000000
max,2023-12-31 00:00:00,10.000000,999.9900,30.000000,5.000000
std,NaN,2.875516,315.2740,9.826206,1.021408

In [50]:
df.describe(include="object")

/var/folders/fn/7d7td86n5c7b7zzdvk9lsr700000gn/T/ipykernel_11779/702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,order_id,customer_name,city,region,category,product,salesperson
count,203,203,203,203,203,203,203
unique,200,152,10,4,4,20,5
top,ORD-1005,Jessica White,San Antonio,South,Furniture,Desk,Emma Davis
freq,2,4,26,88,67,17,50

In [51]:
df['unit_price'].mean()

np.float64(274.1033004926108)

In [52]:
df['unit_price'].min()

np.float64(5.99)

In [53]:
df['unit_price'].max

<bound method Series.max of 0       89.99
1       12.99
2       12.99
3      349.99
4      249.99
        ...
198      9.99
199     69.99
200    999.99
201    149.99
202      9.99
Name: unit_price, Length: 203, dtype: float64>

### ✅ Task 4 — Selecting Columns
1. Select and display only the `customer_name` and `city` columns.
2. Select the columns `product`, `quantity`, `unit_price` and display the **first 10 rows**.
3. Store the `unit_price` column as a **Pandas Series** named `prices_series` and print its type.

In [60]:

df[['customer_name','city']]

        customer_name          city
0      Karen Robinson   San Antonio
1    Michael Williams       Houston
2         Karen Moore        Dallas
3      Michael Martin       Phoenix
4    Jessica Williams   San Antonio
..                ...           ...
198      Robert Brown   Los Angeles
199    Susan Robinson  Philadelphia
200      Susan Thomas       Seattle
201  Michael Robinson  Philadelphia
202       Sarah Davis        Austin

[203 rows x 2 columns]

In [61]:
df[['product','quantity','unit_price']].head(10)

        product  quantity  unit_price
0        Jacket         1       89.99
1     Olive Oil         5       12.99
2     Olive Oil         7       12.99
3          Desk         6      349.99
4  Office Chair         1      249.99
5        Laptop         5      999.99
6        Laptop         5      999.99
7     Bookshelf         6      149.99
8           Tea         3        9.99
9         Jeans         5       59.99

In [62]:
price_series = df['unit_price']
print(type(price_series))

<class 'pandas.Series'>

### ✅ Task 5 — Filtering Rows
Filter and display:
1. All orders from the **'Electronics'** category.
2. All orders where `quantity` is **greater than 7**.
3. All orders from **'New York'** city.
4. Print the **row count** for each filtered result.

In [69]:
ele = df[df['category'] == 'Electronics']

print("Orders in electronics category are:" , ele.shape[0])

Orders in electronics category are: 48

In [68]:
order_count = df[df['quantity'] > 7]
print(order_count.shape[0])

57

In [70]:
newyork = df[df['city'] == 'New York']
print(newyork.shape[0])

23

### ✅ Task 6 — Sorting
1. Sort the DataFrame by `unit_price` in **descending order** and display the top 10 rows.
2. Sort by `category` (ascending) and then by `unit_price` (descending) — **multi-column sort**.
3. Display the **cheapest 5 products** (by unit_price).

In [81]:
df.sort_values(by='unit_price', ascending= False).head(10)
# df['unit_price'].sort_values(ascending= False).head(10)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
167,ORD-1167,2023-11-02 11:12:57.889447,Karen White,Houston,South,Electronics,Laptop,9,999.99,5.0,Emma Davis,3.0
200,ORD-1005,2023-01-10 03:29:50.954773,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
63,ORD-1063,2023-04-26 05:40:06.030150,David Johnson,Seattle,West,Electronics,Laptop,1,999.99,10.0,Carol White,4.0
33,ORD-1033,2023-03-02 08:41:00.301507,Susan Jones,Chicago,North,Electronics,Laptop,6,999.99,20.0,Alice Johnson,5.0
74,ORD-1074,2023-05-16 08:33:46.130653,Linda Thomas,Dallas,South,Electronics,Laptop,2,999.99,10.0,Bob Martinez,NaN
176,ORD-1176,2023-11-18 22:18:41.608040,Linda Thompson,New York,East,Electronics,Laptop,9,999.99,10.0,David Lee,4.0
129,ORD-1129,2023-08-24 23:02:06.633165,Mary Williams,San Antonio,South,Electronics,Laptop,10,999.99,10.0,David Lee,3.0
180,ORD-1180,2023-11-26 05:54:34.371859,Patricia Garcia,San Antonio,South,Electronics,Laptop,5,999.99,0.0,Bob Martinez,4.0
6,ORD-1006,2023-01-11 23:23:49.145728,Mary Williams,Chicago,North,Electronics,Laptop,5,999.99,15.0,Emma Davis,NaN
5,ORD-1005,2023-01-10 03:29:50.954773,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0

In [82]:
df.sort_values(by= ['category' , 'unit_price'] , ascending= [ True , False])

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
56,ORD-1056,2023-04-13 10:22:18.693467,Robert Johnson,Los Angeles,West,Clothing,Jacket,9,89.99,0.0,David Lee,4.0
81,ORD-1081,2023-05-29 03:51:33.467336,Barbara Brown,Austin,South,Clothing,Jacket,7,89.99,15.0,David Lee,4.0
124,ORD-1124,2023-08-15 19:32:15.678391,Sarah Jones,New York,East,Clothing,Jacket,6,89.99,30.0,Carol White,2.0
127,ORD-1127,2023-08-21 07:14:10.251256,John Smith,Phoenix,West,Clothing,Jacket,8,89.99,25.0,David Lee,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
109,ORD-1109,2023-07-19 09:02:42.814070,Susan Miller,Chicago,North,Furniture,Lamp,9,49.99,20.0,David Lee,4.0
152,ORD-1152,2023-10-06 00:43:25.025125,Jennifer Wilson,Philadelphia,East,Furniture,Lamp,4,49.99,25.0,Carol White,3.0
154,ORD-1154,2023-10-09 16:31:21.407035,Daniel Wilson,Austin,South,Furniture,Lamp,4,49.99,0.0,Emma Davis,3.0
172,ORD-1172,2023-11-11 14:42:48.844221,William Garcia,Phoenix,West,Furniture,Lamp,2,49.99,5.0,Alice Johnson,5.0
183,ORD-1183,2023-12-01 17:36:28.944723,David Thompson,New York,East,Furniture,Lamp,7,49.99,5.0,Bob Martinez,4.0

In [85]:
df.sort_values(by='city' , ascending= False).head(5)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
158,ORD-1158,2023-10-17 00:07:14.170854,James Moore,Seattle,West,Clothing,T-Shirt,2,29.99,15.0,Alice Johnson,3.0
120,ORD-1120,2023-08-08 11:56:22.914572,Thomas Jackson,Seattle,West,Food,Coffee Beans,1,14.99,0.0,Emma Davis,4.0
65,ORD-1065,2023-04-29 21:28:02.412060,Linda Jones,Seattle,West,Food,Tea,4,9.99,15.0,Alice Johnson,4.0
22,ORD-1022,2023-02-10 05:47:20.201005,Thomas Moore,Seattle,West,Furniture,Sofa,4,799.99,NaN,Alice Johnson,4.0
135,ORD-1135,2023-09-04 22:25:55.778894,Thomas Jackson,Seattle,West,Clothing,Sneakers,2,79.99,25.0,David Lee,3.0

### ✅ Task 7 — Value Counts
1. Count how many orders belong to each **category**.
2. Count how many orders were handled by each **salesperson**.
3. Find the **most common city** in the dataset.
4. Show the distribution of **customer ratings** (including NaN count).

In [93]:

print(df['category'].value_counts())
print()

category
Furniture      67
Electronics    48
Food           47
Clothing       41
Name: count, dtype: int64

In [92]:

print(df['salesperson'].value_counts())
print()

salesperson
Emma Davis       50
David Lee        48
Bob Martinez     41
Alice Johnson    36
Carol White      28
Name: count, dtype: int64

In [90]:

most_common_city = df['city'].value_counts().idxmax()
city_count = df['city'].value_counts().max()
print(f"City: {most_common_city} (Count: {city_count})")
print()

City: San Antonio (Count: 26)

In [91]:

print(df['rating'].value_counts(dropna=False))

rating
4.0    85
5.0    49
3.0    33
2.0    17
NaN    13
1.0     6
Name: count, dtype: int64

### ✅ Task 8 — Adding a New Column
Add a new column called **`total_revenue`** computed as:
> `total_revenue = quantity × unit_price × (1 - discount / 100)`

> ⚠️ Treat missing `discount` values as **0** (no discount).

Print the first 10 rows showing `product`, `quantity`, `unit_price`, `discount`, and `total_revenue`.

In [94]:

discount_clean = df['discount'].fillna(0)

df['total_revenue'] = df['quantity'] * df['unit_price'] * (1 - discount_clean / 100)

print(df[['product', 'quantity', 'unit_price', 'discount', 'total_revenue']].head(10))

        product  quantity  unit_price  discount  total_revenue
0        Jacket         1       89.99      10.0        80.9910
1     Olive Oil         5       12.99      15.0        55.2075
2     Olive Oil         7       12.99       0.0        90.9300
3          Desk         6      349.99      15.0      1784.9490
4  Office Chair         1      249.99      10.0       224.9910
5        Laptop         5      999.99      20.0      3999.9600
6        Laptop         5      999.99      15.0      4249.9575
7     Bookshelf         6      149.99      20.0       719.9520
8           Tea         3        9.99      30.0        20.9790
9         Jeans         5       59.99       0.0       299.9500

### ✅ Task 9 — Handling Missing Values
1. Count the total number of missing values in the **entire DataFrame**.
2. Fill missing `rating` values with the **median** rating.
3. Fill missing `discount` values with **0**.
4. Confirm there are **no more missing values** after filling.

In [95]:

total_missing = df.isnull().sum().sum()
print(f"Total missing values in the entire DataFrame: {total_missing}")
print()

Total missing values in the entire DataFrame: 21

In [96]:
df['rating'] = df['rating'].fillna(df['rating'].median())
print("Filled missing rating values with median rating.")

Filled missing rating values with median rating.

In [97]:

df['discount'] = df['discount'].fillna(0)
print("Filled missing discount values with 0.")
print()

Filled missing discount values with 0.

In [98]:
missing_after = df.isnull().sum().sum()
print(f"Confirming no more missing values (should be 0): {missing_after}")

Confirming no more missing values (should be 0): 0

### ✅ Task 10 — Removing Duplicates
1. Check how many **duplicate rows** exist in the DataFrame.
2. Display the duplicate rows.
3. Remove duplicates and store the clean DataFrame back into `df`.
4. Confirm the new shape.

In [99]:

num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")
print()

Number of duplicate rows: 3

In [100]:
print("Duplicate rows:")
print(df[df.duplicated()])
print()

Duplicate rows:
     order_id                 order_date     customer_name          city  \
200  ORD-1005 2023-01-10 03:29:50.954773      Susan Thomas       Seattle
201  ORD-1023 2023-02-12 01:41:18.391959  Michael Robinson  Philadelphia
202  ORD-1077 2023-05-21 20:15:40.703517       Sarah Davis        Austin

    region     category    product  quantity  unit_price  discount  \
200   West  Electronics     Laptop         5      999.99      20.0
201   East    Furniture  Bookshelf         1      149.99      10.0
202  South         Food        Tea         2        9.99       5.0

      salesperson  rating  total_revenue
200    Emma Davis     4.0       3999.960
201    Emma Davis     4.0        134.991
202  Bob Martinez     4.0         18.981

In [101]:

df = df.drop_duplicates()
print("Duplicates removed.")
print()

Duplicates removed.

In [102]:

print(f"New shape of the DataFrame: {df.shape}")

New shape of the DataFrame: (200, 13)

### ✅ Task 11 — Renaming and Dropping Columns
1. Rename the column `unit_price` to `price_usd` and `customer_name` to `customer`.
2. Drop the column `order_id` from a **copy** of the DataFrame (do not modify `df`).
3. Reset the index of that copy and print it.

In [5]:

df = df.rename(columns={'unit_price': 'price_usd', 'customer_name': 'customer'})
print("Renamed columns in df:")
print(df.columns)
print()

Renamed columns in df:
Index(['order_id', 'order_date', 'customer', 'city', 'region', 'category',
       'product', 'quantity', 'price_usd', 'discount', 'salesperson',
       'rating'],
      dtype='str')

In [6]:
df_copy = df.copy()
df_copy = df_copy.drop(columns=['order_id'])

In [7]:
df_copy = df_copy.reset_index(drop=True)
print("Reset index copy (showing head):")
print(df_copy.head())

df_copy

Reset index copy (showing head):
                  order_date          customer         city region   category  \
0 2023-01-01 00:00:00.000000    Karen Robinson  San Antonio  South   Clothing
1 2023-01-02 19:53:58.190954  Michael Williams      Houston  South       Food
2 2023-01-04 15:47:56.381909       Karen Moore       Dallas  South       Food
3 2023-01-06 11:41:54.572864    Michael Martin      Phoenix   West  Furniture
4 2023-01-08 07:35:52.763819  Jessica Williams  San Antonio  South  Furniture

        product  quantity  price_usd  discount   salesperson  rating
0        Jacket         1      89.99      10.0     David Lee     5.0
1     Olive Oil         5      12.99      15.0     David Lee     4.0
2     Olive Oil         7      12.99       0.0  Bob Martinez     NaN
3          Desk         6     349.99      15.0     David Lee     5.0
4  Office Chair         1     249.99      10.0    Emma Davis     4.0

,order_date,customer,city,region,category,product,quantity,price_usd,discount,salesperson,rating
0,2023-01-01 00:00:00.000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,2023-01-02 19:53:58.190954,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,2023-01-04 15:47:56.381909,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,2023-01-06 11:41:54.572864,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,2023-01-08 07:35:52.763819,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0
...,...,...,...,...,...,...,...,...,...,...,...
198,2023-12-29 04:06:01.809045,Robert Brown,Los Angeles,West,Food,Tea,4,9.99,0.0,Alice Johnson,4.0
199,2023-12-31 00:00:00.000000,Susan Robinson,Philadelphia,East,Clothing,Dress,6,69.99,10.0,Bob Martinez,NaN
200,2023-01-10 03:29:50.954773,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
201,2023-02-12 01:41:18.391959,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,NaN
202,2023-05-21 20:15:40.703517,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0

### ✅ Task 12 — `loc` and `iloc`
Using the original `df`:
1. Use **`iloc`** to select rows 10 to 20 and the first 4 columns.
2. Use **`loc`** to select all rows where `region == 'West'`, showing only `city`, `product`, and `unit_price`.
3. Use **`loc`** to update the `discount` of row at index `0` to `50`.

In [3]:

print("--- 1. Rows 10 to 20, first 4 columns (using iloc) ---")
result_iloc = df.iloc[10:21, :4]
print(result_iloc)
print()

--- 1. Rows 10 to 20, first 4 columns (using iloc) ---
    order_id                 order_date     customer_name          city
10  ORD-1010 2023-01-19 06:59:41.909547     Charles Brown       Houston
11  ORD-1011 2023-01-21 02:53:40.100502  Richard Thompson        Dallas
12  ORD-1012 2023-01-22 22:47:38.291457      James Harris        Dallas
13  ORD-1013 2023-01-24 18:41:36.482412     Richard Moore       Chicago
14  ORD-1014 2023-01-26 14:35:34.673366     Susan Johnson  Philadelphia
15  ORD-1015 2023-01-28 10:29:32.864321        John Moore       Phoenix
16  ORD-1016 2023-01-30 06:23:31.055276       Mary Thomas   Los Angeles
17  ORD-1017 2023-02-01 02:17:29.246231  Richard Thompson        Dallas
18  ORD-1018 2023-02-02 22:11:27.437185       John Miller  Philadelphia
19  ORD-1019 2023-02-04 18:05:25.628140  Jessica Robinson   Los Angeles
20  ORD-1020 2023-02-06 13:59:23.819095  Charles Anderson       Phoenix

In [8]:
print("--- 2. Rows in 'West' region, showing city, product, and price_usd (using loc) ---")
result_loc = df.loc[df['region'] == 'West', ['city', 'product', 'price_usd']]
print(result_loc.head(10))
print()

--- 2. Rows in 'West' region, showing city, product, and price_usd (using loc) ---
           city     product  price_usd
3       Phoenix        Desk     349.99
5       Seattle      Laptop     999.99
9       Phoenix       Jeans      59.99
15      Phoenix   Chocolate       8.99
16  Los Angeles        Desk     349.99
19  Los Angeles         Tea       9.99
20      Phoenix   Chocolate       8.99
22      Seattle        Sofa     799.99
26      Seattle  Smartphone     799.99
32      Phoenix        Desk     349.99

In [9]:
df.loc[0, 'discount'] = 50
print("--- 3. Updated discount of row at index 0 to 50 ---")
print(df.loc[[0], ['customer', 'discount']])

--- 3. Updated discount of row at index 0 to 50 ---
         customer  discount
0  Karen Robinson      50.0